---
- name: install nodejs packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - npm

- name: install npm tools
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - gulp-cli
    - bower
