# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
  app.default_controller:
    class: AppBundle\Controller\DefaultController
    arguments:
      - '@templating'

  app.minecraft_controller:
    class: AppBundle\Controller\MinecraftController
    arguments:
      - '@templating'
      - '@app.minecraft.client'

  app.minecraft.guzzle_client:
    class: GuzzleHttp\Client

  app.minecraft.guzzle_adapter:
    class: Http\Adapter\Guzzle6\Client
    arguments:
      - '@app.minecraft.guzzle_client'

  app.minecraft.message_factory:
    class: Http\Message\MessageFactory\GuzzleMessageFactory
    factory: ["Http\\Discovery\\MessageFactoryDiscovery", find]

  app.minecraft.request_factory:
    class: AppBundle\Minecraft\RequestFactory
    arguments:
      - '@app.minecraft.message_factory'
      - '%minecraft_host%'
      - '%minecraft_secret%'

  app.minecraft.client:
    class: AppBundle\Minecraft\Client
    arguments:
      - '@app.minecraft.guzzle_adapter'
      - '@app.minecraft.request_factory'
      - '@jms_serializer.serializer'
