# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
  app.minecraft.guzzle_client:
    class: GuzzleHttp\Client

  app.minecraft.guzzle_adapter:
    class: Http\Adapter\Guzzle6\Client
    arguments:
      - '@app.minecraft.guzzle_client'

  app.minecraft.message_factory:
    class: Http\Message\MessageFactory\GuzzleMessageFactory
    factory: ["Http\\Discovery\\MessageFactoryDiscovery", find]

  app.minecraft.client:
    class: AppBundle\Minecraft\Client
    arguments:
      - '@app.minecraft.guzzle_adapter'
      - '@app.minecraft.message_factory'
      - '@serializer'
      - '%minecraft_host%'
      - '%minecraft_secret%'
