---
- name: Install mysql packages.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: ensure mysql user
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    priv: "{{ item.priv }}"
    state: present
  with_items: "{{ mysql_users }}"

- name: ensure databases
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_databases }}"

- name: ensure bind-address is set
  ini_file:
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: bind-address
    value: '{{ mysql_bind_ip }}'
    mode: 0644
  notify: restart mysql

- name: ensure mysql started and enabled
  service:
    name: mysql
    enabled: true
