---
- hosts: all
  tasks:
    - debug: var=hostvars

- hosts: devbox
  pre_tasks:
    - apt:
        update_cache: true
      become: true
  roles:
    - role: mysql
      become: true
    - role: nginx
      become: true
    - role: app
      become: true
    - role: varnish
      become: true
    - role: tools
      become: true
