---
mysql_bind_ip: 0.0.0.0
mysql_users:
  -
    name: minecraft
    password: "{{ lookup('env','APP_MYSQL_PASSWORD')|default('') }}"
    host: '%'
    priv: '*.*:ALL'
mysql_databases:
    - minecraft
    - minecraft_test
